[tool.ruff]
include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]

# Using python 3.11
target-version = "py311"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "D",
    "I",
    "UP",
    "YTT",
    "FBT",
    "B",
    "A",
    "C",
    "EM",
    "ICN",
    "ISC",
    "T20",
    "PT",
    "Q",
    "RET",
    "SIM",
    "TID",
    "ARG",
    "PD",
    "PIE",
    "N",
]

ignore = [
    "D100",   # D100 : Missing docstring in public module
    "D101",   # D101 : Missing docstring in public class
    "D102",   # D102 : Missing docstring in public method
    "D103",   # D103 : Missing docstring in public function
    "D104",   # D104 : Missing docstring in public package
    "D105",   # D105 : Missing docstring in magic method
    "D107",   # D107 : Missing docstring in __init__
    "F401",   # F401 : Imported but unused
    "E501",   # E501 : Line too long
    "C901",   # C901 : Function is too complex
    "RET505", # RET505 : Unnecessary `elif` after `return` statement
    "PD901",  # PD901 : `df` is a bad variable name. Be kinder to your future self.
    "PT009",  # PT009 : Use a regular `assert` instead of unittest-style `assertEqual`
]

unfixable = [
    "E712", # E712 : Comparison to True should be 'if cond is True:' or 'if cond:'
]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.lint.pydocstyle]
convention = "google" # Accepts: "google", "numpy", or "pep257".

[tool.ruff.lint.per-file-ignores]
"src/betaseries_recommender/cli.py" = ["T201"]
